version: "3.7"
services:
    jenkins:
        container_name: sgbg-jenkins
        image: jenkins/jenkins:lts
        ports:
            - "8888:8080"
        volumes:
            -  /home/ubuntu/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
    nginx:
        container_name: sgbg-nginx
        build:
            context: .
        depends_on:
            - server
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data/nginx/conf:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        restart: always
    certbot:
        container_name: sgbg-certbot
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    mysql-db:
        container_name: sgbg-mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=Tkvl7rldbryqhdlsmsdlswjddlwl
            - MYSQL_DATABASE=sgbg
            - MYSQL_USER=ugyo-boi
            - MYSQL_PASSWORD=vktmfflrkqhwkrh
        command:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
        restart: always
    redis:
        container_name: sgbg-redis
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
        restart: on-failure
    server:
        container_name: sgbg-server
        depends_on:
            - mysql-db
            - redis
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        restart: on-failure
